### PR TITLE
Week 7

### PR DESCRIPTION
**Pull request by savithaR24**
**Country Info App - Flows**
- Restructures the API call to be behind a method that utilizes a flow { } block.  The call site collects the data and catches any exceptions.
- Creates and utilizes three StateFlows in a singleton object for: 1) country info list item taps, 2) tapping the back button from the details screen, and 3) an app uptime counter.
- The singleton object flow objects are properly exposed as StateFlow and are val.
- Row that shows the current tap count, back count and refresh button.
- The app uptime display on the Loading page in the app.

### CODE REVIEW

**Review by byaruhaf — APPROVED** [review]
Excellent work, see comments in Google Docs 
Ready to merge

**Comment by savithaR24** [comment]
> Excellent work, see comments in Google Docs Ready to merge

Thanks a lot for reviewing @byaruhaf. Had two of the three Above & Beyond tasks completed i.e extra flow and combine flows. Thought a lot on the third one which is sharedFlow but could not find a use case in this app. So, didn't get that one in. If you could please consider this for my grading, would be wonderful. Thanks again.

**Comment by byaruhaf** [comment]
@savithaR24  After consulting with the other mentor grade upgraded to Above & Beyond

**Comment by savithaR24** [comment]
> @savithaR24 After consulting with the other mentor grade upgraded to Above & Beyond

Thank you so much! @byaruhaf

**Pull request merged**
